-- Phase 2 (P2-01/P2-02/P2-06): RBAC role alignment and permission seeding.
--
-- Generated by hand from src/common/authz/rbac.ts. The parity test
-- (src/common/authz/rbac-catalog.spec.ts) fails if this file and the catalog
-- drift apart.
--
-- 1. Deliberate migration of the combined "admin_staff" role:
--    the role row is renamed to "registrar", which preserves every existing
--    user/audit reference through role_id. No rows are deleted.
-- 2. Adds the "treasury" role and ensures every canonical role exists.
-- 3. Seeds the action/resource permission catalog.
-- 4. Maps roles to permissions per the thesis permission model (DEC-001).

-- ---------------------------------------------------------------------------
-- 1. Rename the combined Registrar/Accounting role (deliberate migration).
-- ---------------------------------------------------------------------------
UPDATE "roles" SET "name" = 'registrar' WHERE "name" = 'admin_staff';

-- ---------------------------------------------------------------------------
-- 2. Ensure every canonical role exists.
-- ---------------------------------------------------------------------------
INSERT INTO "roles" ("id", "name", "created_at")
VALUES
  (gen_random_uuid(), 'student', now()),
  (gen_random_uuid(), 'faculty', now()),
  (gen_random_uuid(), 'dean', now()),
  (gen_random_uuid(), 'registrar', now()),
  (gen_random_uuid(), 'treasury', now()),
  (gen_random_uuid(), 'sys_admin', now()),
  (gen_random_uuid(), 'live_agent', now())
ON CONFLICT ("name") DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Permission catalog (resource + action).
-- ---------------------------------------------------------------------------
INSERT INTO "permissions" ("id", "action", "resource", "created_at")
VALUES
  (gen_random_uuid(), 'read_own', 'student_record', now()),
  (gen_random_uuid(), 'read_assigned', 'student_record', now()),
  (gen_random_uuid(), 'update', 'student_record', now()),
  (gen_random_uuid(), 'read_own', 'enrollment', now()),
  (gen_random_uuid(), 'process', 'enrollment', now()),
  (gen_random_uuid(), 'read_own', 'financial', now()),
  (gen_random_uuid(), 'manage', 'financial', now()),
  (gen_random_uuid(), 'create', 'service_request', now()),
  (gen_random_uuid(), 'process', 'service_request', now()),
  (gen_random_uuid(), 'use', 'aria', now()),
  (gen_random_uuid(), 'read', 'aria_trends', now()),
  (gen_random_uuid(), 'manage', 'knowledge_base', now()),
  (gen_random_uuid(), 'read', 'report', now()),
  (gen_random_uuid(), 'manage', 'user', now()),
  (gen_random_uuid(), 'manage', 'role', now()),
  (gen_random_uuid(), 'read', 'audit', now())
ON CONFLICT ("action", "resource") DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. Role → permission mapping (reviewed thesis permission model).
-- ---------------------------------------------------------------------------

-- student
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'student'
  AND (p."resource" || '.' || p."action") IN ('student_record.read_own', 'enrollment.read_own', 'financial.read_own', 'service_request.create', 'aria.use')
ON CONFLICT DO NOTHING;

-- faculty
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'faculty'
  AND (p."resource" || '.' || p."action") IN ('student_record.read_assigned')
ON CONFLICT DO NOTHING;

-- dean
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'dean'
  AND (p."resource" || '.' || p."action") IN ('student_record.read_assigned', 'aria_trends.read', 'report.read')
ON CONFLICT DO NOTHING;

-- registrar
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'registrar'
  AND (p."resource" || '.' || p."action") IN ('student_record.read_assigned', 'student_record.update', 'enrollment.process', 'service_request.process', 'knowledge_base.manage', 'report.read')
ON CONFLICT DO NOTHING;

-- treasury
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'treasury'
  AND (p."resource" || '.' || p."action") IN ('financial.manage', 'report.read')
ON CONFLICT DO NOTHING;

-- sys_admin (all catalog permissions)
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'sys_admin'
  AND (p."resource" || '.' || p."action") IN ('student_record.read_own', 'student_record.read_assigned', 'student_record.update', 'enrollment.read_own', 'enrollment.process', 'financial.read_own', 'financial.manage', 'service_request.create', 'service_request.process', 'aria.use', 'aria_trends.read', 'knowledge_base.manage', 'report.read', 'user.manage', 'role.manage', 'audit.read')
ON CONFLICT DO NOTHING;

-- live_agent: supporting ARIA escalation role, no catalog permissions.
